- name: Append filtered records to /etc/hosts on remote servers
  hosts: slurm-node
  become: yes

  tasks:
    - name: Read and filter the local hosts file
      shell: egrep -v '^127|::' /etc/hosts | egrep -v '^\s*$'
      register: filtered_hosts
      changed_when: false
      delegate_to: localhost

    - name: Append filtered records to remote /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop: "{{ filtered_hosts.stdout_lines }}"