---
- hosts: all
  become: yes
  tasks:
    # Install python required for Ansible
    - import_tasks: bootstrap/bootstrap-python.yml

    # Set up passwordless sudo and SSH keys if needed
    - import_tasks: bootstrap/bootstrap-ssh.yml

    - import_tasks: bootstrap/bootstrap-sudo.yml


    # Configure hostnames, /etc/hosts
    - import_tasks: generic/hosts.yml
      when: "{{ slurm_configure_etc_hosts | default(true) }}"
      tags:
        - set-etc-hosts

    # Install Node Health Check
    - import_tasks: slurm-cluster/nhc.yml
      vars:
        hostlist: slurm-node
      when: slurm_install_nhc | default(false)

    # Install Slurm
    - import_tasks: slurm-cluster/slurm.yml

    # Install Enroot and Pyxis
    - import_tasks: container/pyxis.yml
      when:
        - slurm_install_enroot
        - slurm_install_pyxis
      tags:
        - pyxis